
Ingredient.create(name: "lemon")
Ingredient.create(name: "banana")
Ingredient.create(name: "strawberry")
Ingredient.create(name: "mint")
Ingredient.create(name: "vodka")
Ingredient.create(name: "whisky")
Ingredient.create(name: "beer")
Ingredient.create(name: "gin")
Ingredient.create(name: "tonic")
Ingredient.create(name: "salt")
Ingredient.create(name: "rum")

Cocktail.create(name: "Moscow Mule")
Cocktail.create(name: "Whisky Sour")
Cocktail.create(name: "Mojito")
Cocktail.create(name: "Daiquiri")
Cocktail.create(name: "Margarita")
Cocktail.create(name: "Bloody Mary")
Cocktail.create(name: "Cosmopolitan")
Cocktail.create(name: "Tom Collins")
Cocktail.create(name: "Manhattan")
Cocktail.create(name: "Hangman's Blood")
Cocktail.create(name: "Irish Car bomb")
Cocktail.create(name: "Shandy")
Cocktail.create(name: "Blackthorn")
